// This is the backend code for reading and writing

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using TestNew;

namespace UnityEngine
{
    public static class Vector3Serializer
    {
        /// <summary>Helper: create a new instance to deserializing into</summary>
        public static Vector3 Deserialize(Stream stream)
        {
            Vector3 instance = new Vector3();
            Deserialize(stream, ref instance);
            return instance;
        }

        /// <summary>Helper: create a new instance to deserializing into</summary>
        public static Vector3 DeserializeLengthDelimited(Stream stream)
        {
            Vector3 instance = new Vector3();
            DeserializeLengthDelimited(stream, ref instance);
            return instance;
        }

        /// <summary>Helper: create a new instance to deserializing into</summary>
        public static Vector3 DeserializeLength(Stream stream, int length)
        {
            Vector3 instance = new Vector3();
            DeserializeLength(stream, length, ref instance);
            return instance;
        }

        /// <summary>Helper: put the buffer into a MemoryStream and create a new instance to deserializing into</summary>
        public static Vector3 Deserialize(byte[] buffer)
        {
            Vector3 instance = new Vector3();
            using (var ms = new MemoryStream(buffer))
                Deserialize(ms, ref instance);
            return instance;
        }

        /// <summary>Helper: put the buffer into a MemoryStream before deserializing</summary>
        public static UnityEngine.Vector3 Deserialize(byte[] buffer, ref UnityEngine.Vector3 instance)
        {
            using (var ms = new MemoryStream(buffer))
                Deserialize(ms, ref instance);
            return instance;
        }

        /// <summary>Takes the remaining content of the stream and deserialze it into the instance.</summary>
        public static UnityEngine.Vector3 Deserialize(Stream stream, ref UnityEngine.Vector3 instance)
        {
            while (true)
            {
                int keyByte = stream.ReadByte();
                if (keyByte == -1)
                    break;
                // Optimized reading of known fields with field ID < 16
                switch (keyByte)
                {
                    // Field 1 Fixed32
                    case 13:
                        instance.x = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                    // Field 2 Fixed32
                    case 21:
                        instance.y = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                    // Field 3 Fixed32
                    case 29:
                        instance.z = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                }

                var key = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadKey((byte)keyByte, stream);

                // Reading field ID > 16 and unknown field ID/wire type combinations
                switch (key.Field)
                {
                    case 0:
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Invalid field id: 0, something went wrong in the stream");
                    default:
                        global::SilentOrbit.ProtocolBuffers.ProtocolParser.SkipKey(stream, key);
                        break;
                }
            }

            return instance;
        }

        /// <summary>Read the VarInt length prefix and the given number of bytes from the stream and deserialze it into the instance.</summary>
        public static UnityEngine.Vector3 DeserializeLengthDelimited(Stream stream, ref UnityEngine.Vector3 instance)
        {
            long limit = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadUInt32(stream);
            limit += stream.Position;
            while (true)
            {
                if (stream.Position >= limit)
                {
                    if (stream.Position == limit)
                        break;
                    else
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Read past max limit");
                }
                int keyByte = stream.ReadByte();
                if (keyByte == -1)
                    throw new System.IO.EndOfStreamException();
                // Optimized reading of known fields with field ID < 16
                switch (keyByte)
                {
                    // Field 1 Fixed32
                    case 13:
                        instance.x = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                    // Field 2 Fixed32
                    case 21:
                        instance.y = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                    // Field 3 Fixed32
                    case 29:
                        instance.z = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                }

                var key = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadKey((byte)keyByte, stream);

                // Reading field ID > 16 and unknown field ID/wire type combinations
                switch (key.Field)
                {
                    case 0:
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Invalid field id: 0, something went wrong in the stream");
                    default:
                        global::SilentOrbit.ProtocolBuffers.ProtocolParser.SkipKey(stream, key);
                        break;
                }
            }

            return instance;
        }

        /// <summary>Read the given number of bytes from the stream and deserialze it into the instance.</summary>
        public static UnityEngine.Vector3 DeserializeLength(Stream stream, int length, ref UnityEngine.Vector3 instance)
        {
            long limit = stream.Position + length;
            while (true)
            {
                if (stream.Position >= limit)
                {
                    if (stream.Position == limit)
                        break;
                    else
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Read past max limit");
                }
                int keyByte = stream.ReadByte();
                if (keyByte == -1)
                    throw new System.IO.EndOfStreamException();
                // Optimized reading of known fields with field ID < 16
                switch (keyByte)
                {
                    // Field 1 Fixed32
                    case 13:
                        instance.x = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                    // Field 2 Fixed32
                    case 21:
                        instance.y = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                    // Field 3 Fixed32
                    case 29:
                        instance.z = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadSingle(stream);
                        continue;
                }

                var key = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadKey((byte)keyByte, stream);

                // Reading field ID > 16 and unknown field ID/wire type combinations
                switch (key.Field)
                {
                    case 0:
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Invalid field id: 0, something went wrong in the stream");
                    default:
                        global::SilentOrbit.ProtocolBuffers.ProtocolParser.SkipKey(stream, key);
                        break;
                }
            }

            return instance;
        }

        /// <summary>Serialize the instance into the stream</summary>
        public static void Serialize(Stream stream, Vector3 instance)
        {
            var msField = Pool.Get<MemoryStream>();
            // Key for field: 1, Fixed32
            stream.WriteByte(13);
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteSingle(stream, instance.x);
            // Key for field: 2, Fixed32
            stream.WriteByte(21);
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteSingle(stream, instance.y);
            // Key for field: 3, Fixed32
            stream.WriteByte(29);
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteSingle(stream, instance.z);
            Pool.FreeMemoryStream(ref msField);
        }

        /// <summary>Helper: Serialize into a MemoryStream and return its byte array</summary>
        public static byte[] SerializeToBytes(Vector3 instance)
        {
            using (var ms = new MemoryStream())
            {
                Serialize(ms, instance);
                return ms.ToArray();
            }
        }
        /// <summary>Helper: Serialize with a varint length prefix</summary>
        public static void SerializeLengthDelimited(Stream stream, Vector3 instance)
        {
            var data = SerializeToBytes(instance);
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteUInt32(stream, (uint)data.Length);
            stream.Write(data, 0, data.Length);
        }
    }

}
namespace Despunch.Data
{
    public partial class InputState
    {
        /// <summary>Helper: create a new instance to deserializing into</summary>
        public static InputState Deserialize(Stream stream)
        {
            InputState instance = new InputState();
            Deserialize(stream, instance);
            return instance;
        }

        /// <summary>Helper: create a new instance to deserializing into</summary>
        public static InputState DeserializeLengthDelimited(Stream stream)
        {
            InputState instance = new InputState();
            DeserializeLengthDelimited(stream, instance);
            return instance;
        }

        /// <summary>Helper: create a new instance to deserializing into</summary>
        public static InputState DeserializeLength(Stream stream, int length)
        {
            InputState instance = new InputState();
            DeserializeLength(stream, length, instance);
            return instance;
        }

        /// <summary>Helper: put the buffer into a MemoryStream and create a new instance to deserializing into</summary>
        public static InputState Deserialize(byte[] buffer)
        {
            InputState instance = new InputState();
            using (var ms = new MemoryStream(buffer))
                Deserialize(ms, instance);
            return instance;
        }

        /// <summary>Helper: put the buffer into a MemoryStream before deserializing</summary>
        public static Despunch.Data.InputState Deserialize(byte[] buffer, Despunch.Data.InputState instance)
        {
            using (var ms = new MemoryStream(buffer))
                Deserialize(ms, instance);
            return instance;
        }

        /// <summary>Takes the remaining content of the stream and deserialze it into the instance.</summary>
        public static Despunch.Data.InputState Deserialize(Stream stream, Despunch.Data.InputState instance)
        {
            while (true)
            {
                int keyByte = stream.ReadByte();
                if (keyByte == -1)
                    break;
                // Optimized reading of known fields with field ID < 16
                switch (keyByte)
                {
                    // Field 1 Varint
                    case 8:
                        instance.buttons = (int)global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadUInt64(stream);
                        continue;
                    // Field 2 LengthDelimited
                    case 18:
                        UnityEngine.Vector3Serializer.DeserializeLengthDelimited(stream, ref instance.aimAngles);
                        continue;
                    // Field 3 LengthDelimited
                    case 26:
                        UnityEngine.Vector3Serializer.DeserializeLengthDelimited(stream, ref instance.mouseDelta);
                        continue;
                }

                var key = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadKey((byte)keyByte, stream);

                // Reading field ID > 16 and unknown field ID/wire type combinations
                switch (key.Field)
                {
                    case 0:
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Invalid field id: 0, something went wrong in the stream");
                    default:
                        global::SilentOrbit.ProtocolBuffers.ProtocolParser.SkipKey(stream, key);
                        break;
                }
            }

            return instance;
        }

        /// <summary>Read the VarInt length prefix and the given number of bytes from the stream and deserialze it into the instance.</summary>
        public static Despunch.Data.InputState DeserializeLengthDelimited(Stream stream, Despunch.Data.InputState instance)
        {
            long limit = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadUInt32(stream);
            limit += stream.Position;
            while (true)
            {
                if (stream.Position >= limit)
                {
                    if (stream.Position == limit)
                        break;
                    else
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Read past max limit");
                }
                int keyByte = stream.ReadByte();
                if (keyByte == -1)
                    throw new System.IO.EndOfStreamException();
                // Optimized reading of known fields with field ID < 16
                switch (keyByte)
                {
                    // Field 1 Varint
                    case 8:
                        instance.buttons = (int)global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadUInt64(stream);
                        continue;
                    // Field 2 LengthDelimited
                    case 18:
                        UnityEngine.Vector3Serializer.DeserializeLengthDelimited(stream, ref instance.aimAngles);
                        continue;
                    // Field 3 LengthDelimited
                    case 26:
                        UnityEngine.Vector3Serializer.DeserializeLengthDelimited(stream, ref instance.mouseDelta);
                        continue;
                }

                var key = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadKey((byte)keyByte, stream);

                // Reading field ID > 16 and unknown field ID/wire type combinations
                switch (key.Field)
                {
                    case 0:
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Invalid field id: 0, something went wrong in the stream");
                    default:
                        global::SilentOrbit.ProtocolBuffers.ProtocolParser.SkipKey(stream, key);
                        break;
                }
            }

            return instance;
        }

        /// <summary>Read the given number of bytes from the stream and deserialze it into the instance.</summary>
        public static Despunch.Data.InputState DeserializeLength(Stream stream, int length, Despunch.Data.InputState instance)
        {
            long limit = stream.Position + length;
            while (true)
            {
                if (stream.Position >= limit)
                {
                    if (stream.Position == limit)
                        break;
                    else
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Read past max limit");
                }
                int keyByte = stream.ReadByte();
                if (keyByte == -1)
                    throw new System.IO.EndOfStreamException();
                // Optimized reading of known fields with field ID < 16
                switch (keyByte)
                {
                    // Field 1 Varint
                    case 8:
                        instance.buttons = (int)global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadUInt64(stream);
                        continue;
                    // Field 2 LengthDelimited
                    case 18:
                        UnityEngine.Vector3Serializer.DeserializeLengthDelimited(stream, ref instance.aimAngles);
                        continue;
                    // Field 3 LengthDelimited
                    case 26:
                        UnityEngine.Vector3Serializer.DeserializeLengthDelimited(stream, ref instance.mouseDelta);
                        continue;
                }

                var key = global::SilentOrbit.ProtocolBuffers.ProtocolParser.ReadKey((byte)keyByte, stream);

                // Reading field ID > 16 and unknown field ID/wire type combinations
                switch (key.Field)
                {
                    case 0:
                        throw new global::SilentOrbit.ProtocolBuffers.ProtocolBufferException("Invalid field id: 0, something went wrong in the stream");
                    default:
                        global::SilentOrbit.ProtocolBuffers.ProtocolParser.SkipKey(stream, key);
                        break;
                }
            }

            return instance;
        }

        /// <summary>Serialize the instance into the stream</summary>
        public static void Serialize(Stream stream, InputState instance)
        {
            var msField = Pool.Get<MemoryStream>();
            // Key for field: 1, Varint
            stream.WriteByte(8);
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteUInt64(stream,(ulong)instance.buttons);
            // Key for field: 2, LengthDelimited
            stream.WriteByte(18);
            ﻿msField.SetLength(0);
            UnityEngine.Vector3Serializer.Serialize(msField, instance.aimAngles);
            // Length delimited byte array
            uint length2 = (uint)msField.Length;
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteUInt32(stream, length2);
            stream.Write(msField.GetBuffer(), 0, (int)length2);

            // Key for field: 3, LengthDelimited
            stream.WriteByte(26);
            ﻿msField.SetLength(0);
            UnityEngine.Vector3Serializer.Serialize(msField, instance.mouseDelta);
            // Length delimited byte array
            uint length3 = (uint)msField.Length;
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteUInt32(stream, length3);
            stream.Write(msField.GetBuffer(), 0, (int)length3);

            Pool.FreeMemoryStream(ref msField);
        }

        /// <summary>Helper: Serialize into a MemoryStream and return its byte array</summary>
        public static byte[] SerializeToBytes(InputState instance)
        {
            using (var ms = new MemoryStream())
            {
                Serialize(ms, instance);
                return ms.ToArray();
            }
        }
        /// <summary>Helper: Serialize with a varint length prefix</summary>
        public static void SerializeLengthDelimited(Stream stream, InputState instance)
        {
            var data = SerializeToBytes(instance);
            global::SilentOrbit.ProtocolBuffers.ProtocolParser.WriteUInt32(stream, (uint)data.Length);
            stream.Write(data, 0, data.Length);
        }
    }

}
